import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Fine Tuning',
      items: [
        {
          type: 'autogenerated',
          dirName: 'fine_tuning',
        },
      ]
    }
  ],
  handson: [
    {
      type: 'autogenerated',
      dirName: 'hands_on',
    },
  ],
  triedit: [
    {
      type: 'autogenerated',
      dirName: 'tried_it',
    },
  ]
};

export default sidebars;
